apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: drecoak-io-tls
spec:
  secretName: drecoak-io
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: drecoak.io
  dnsNames:
    - drecoak.io
    - www.drecoak.io
